#!/usr/bin/env python3
"""file_census.py — which harness files each GATE EXECUTES, and by the kind of
the gate (BBX-25: a generic thing needs two instances; R39).

    python3 -m bbx.file_census --self   [--out DIR] [--document PATH] [--check]
                                        [--frozen PATH] [--freeze]
    python3 -m bbx.file_census --root DIR --out DIR [--document PATH] [--check]
                                        [--frozen PATH] [--freeze]
                                        [--only g1,g2] [--insert-after-shebang]
                                        [--shadow-refreeze "<command>"] [--reuse]
    python3 -m bbx.file_census --self --frozen PATH --check-register    (cheap: no shadow, R47)

Measured at RUNTIME, never by reading the gates' text. A shadow git tree is
built from the root's HEAD (`git archive`); every `bin/*`, `drivers/*.sh` and
`lib/sh/*.sh` in it gets one line that appends its own path to a trace file,
and a `lib/py/sitecustomize.py` appends every `lib/py/bbx/*.py` module loaded
(and a module run as a script) at interpreter exit. Every registered gate then
runs once, alone, with a fresh trace. A file's CATEGORY is the set of kinds of
the gates that executed it.

WHY NOT A GREP over the gates' text: measured at bbx-19 over this tree, a rule
that reads each gate's consumer configs instead of its trace mis-files FIVE of
29 gates — `gates/config.sh` and `gates/readout.sh` read frame-driven because
their SYNTHETIC fixtures name a `bbh.toml`, and `gates/temporal.sh`,
`gates/thresholds.sh` and `gates/compare_dispatch.sh` read kernel because they
call the temporal comparators directly with no consumer config at all. The
census document's own method paragraph declined the same shortcut at bbx-11 on
the word `masked`. The trace is the instrument; the text is a witness
(BBX-28).

A GATE'S KIND, derived — never a hand list (BBX-9):

  F / D / C   the gate executed a SEED of that kind. A seed is a harness file
              the kind profile NAMES and no other kind profile names: the
              modules its comparator families reach (the families come from
              `[expectations].kinds`, the modules from `lib/sh/compare.sh`'s
              own dispatch case, followed through the functions it calls), the
              module its `[suite].log_summary` names, its `[suite].driver`,
              and the driver of every tracked consumer config of that kind.
  F also      a gate in the STATIC registry whose body, comments stripped,
              names the `[registries].static_needs_env` variable: it needs the
              lineage tree, which is the frame-driven kind's SUBJECT. Measured
              2026-09-12: this reproduces bbx-11's hand list exactly —
              `fidelity_bbh` 4 mentions, `fidelity_bbh_s2` 5, `suite` 10,
              `census_recount` 0.
  K           kernel — BBX as its own subject — when no seed and no need.

Limit, declared rather than discovered: `propose_temporal.py` is not a seed
under this derivation (the proposer is not reached from the dispatcher's case),
where bbx-11's hand list had it. Measured not to matter: all three gates that
execute it also execute `compare_flicker`, `compare_window` and
`compare_composite`, so their kind is unchanged. A kind whose ONLY distinct
module is a proposer would read K and the gate's own rows would say so.

A gate that is not PASS in the shadow CONTAMINATES its trace: the run is
REFUSED (exit 1) naming the gate, never adjusted (CLAUDE.md §1). That refusal
is also the portable gate's control on the instrument — `--insert-after-shebang`
reproduces gotcha G25, where the trace line was inserted right after the
shebang and so ENDED the header under R30, and a gate that reads its own
header's `NOT-ASSERTED:` lines goes red.

First written at bbx-19 (2026-09-12, S4 step 6), lifting the scratchpad
instrument of bbx-11 recorded in `docs/census/bbx_files.md` §C.
"""
import os
import re
import subprocess
import sys
import time

from . import config as C

BEGIN = "<!-- GENERATED by `bbx file-census`: BEGIN. Never hand-edited (BBX-21). -->"
END = "<!-- GENERATED by `bbx file-census`: END. -->"
LETTER = {"frame-driven": "F", "document-set": "D", "command-line": "C"}
CATEGORIES = [
    ("shared (frame AND document-set AND command-line)", lambda c: {"F", "D", "C"} <= c),
    ("frame-driven and document-set", lambda c: {"F", "D"} <= c),
    ("frame-driven and command-line", lambda c: {"F", "C"} <= c),
    ("document-set and command-line", lambda c: {"D", "C"} <= c),
    ("frame-driven only", lambda c: c & {"F"} and not c & {"K"}),
    ("frame-driven only (+kernel)", lambda c: c & {"F"}),
    ("document-set only", lambda c: c & {"D"} and not c & {"K"}),
    ("document-set only (+kernel)", lambda c: c & {"D"}),
    ("command-line only", lambda c: c & {"C"} and not c & {"K"}),
    ("command-line only (+kernel)", lambda c: c & {"C"}),
    ("kernel only", lambda c: c & {"K"}),
    ("REACHED BY NO GATE", lambda c: True),
]


def run(args, cwd=None, env=None):
    return subprocess.run(args, cwd=cwd, env=env, capture_output=True, text=True)


def git(root, *args):
    r = run(["git", "-C", root, *args])
    if r.returncode:
        raise RuntimeError(f"git {' '.join(args)} in {root}: {r.stderr.strip()}")
    return r.stdout


def uncomment(path):
    try:
        with open(path, errors="replace") as f:
            return "\n".join(l for l in f.read().splitlines()
                             if not l.lstrip().startswith("#"))
    except OSError:
        return ""


ID_TREES = ("HEAD:bin", "HEAD:lib", "HEAD:drivers", "HEAD:gates")


def identity(root):
    """THE SUBJECT'S IDENTITY — R38's whole-set key, not HEAD.

    HEAD is the wrong key for a census that LIVES IN THE TREE it describes: the
    commit that writes the regenerated document moves HEAD, so `--check` would
    fail on its own output for ever after (measured at bbx-19, the gate's own
    first red). The key is the tree hash of `bin`, `lib`, `drivers` and `gates`
    hashed into one, exactly as `fixture/selfgates/subject/idkey.sh wholeset`
    computes it for the self subject: a docs-only commit leaves it unchanged,
    and a commit that touches the harness moves it — which is precisely when
    the census IS stale. The two writers are proven to agree on BBX's own tree
    by `gates/file_census_tool.sh`. Registered as default D62."""
    import hashlib
    text = git(root, "rev-parse", *ID_TREES)
    return hashlib.sha1(text.encode()).hexdigest()


def universe(root):
    """The tracked, non-markdown files under lib/, bin/, drivers/ — §A row A1."""
    out = git(root, "ls-files", "lib", "bin", "drivers").split()
    return [p for p in out if not p.endswith(".md")]


def registries(root, cfg):
    def read(key):
        rel = C.get(cfg, f"registries.{key}")
        p = os.path.join(root, rel)
        if not os.path.exists(p):
            return []
        with open(p) as f:
            return [l.split("#")[0].strip() for l in f if l.split("#")[0].strip()]
    return read("portable"), read("static")


# ---------------------------------------------------------------- the seeds

def family_modules(root):
    """family word -> the bbx modules `lib/sh/compare.sh` reaches for it.

    Read from the dispatcher's own case and its functions, so a new family is
    a new row there and nowhere else (R23)."""
    p = os.path.join(root, "lib", "sh", "compare.sh")
    if not os.path.exists(p):
        return {}
    src = open(p, errors="replace").read()
    funcs = dict(re.findall(r"(?m)^([a-z_][a-z0-9_]*)\(\)\s*\{\n(.*?)\n\}", src, re.S))
    fam2fn = dict(re.findall(r"(?m)^\s+([a-z-]+)\)\s+(compare_[a-z]+)\s", src))

    def mods(fn, seen):
        if fn in seen or fn not in funcs:
            return set()
        seen.add(fn)
        body = funcs[fn]
        found = set(re.findall(r"bbx\.([a-z_]+)", body))
        for other in funcs:
            if other != fn and re.search(r"(^|[;&|(\s])" + other + r"(\s|$)", body, re.M):
                found |= mods(other, seen)
        return found
    return {fam: mods(fn, set()) for fam, fn in fam2fn.items()}


def named_by_kind(root, univ):
    """letter -> the universe files that kind's profile and consumers NAME."""
    fams = family_modules(root)
    inuniv = set(univ)
    named = {L: set() for L in LETTER.values()}

    def add(letter, rel):
        if rel in inuniv:
            named[letter].add(rel)

    for kind, letter in LETTER.items():
        prof = C.KINDS.get(kind, {})
        rows = prof.get("expectations", {}).get("kinds") or C.DEFAULTS["expectations"]["kinds"]
        for fam in {r[1] for r in rows if r[1] in fams}:
            for m in fams[fam]:
                add(letter, f"lib/py/bbx/{m}.py")
        suite = prof.get("suite", {})
        for m in re.findall(r"bbx\.([a-z_]+)", suite.get("log_summary", "") or ""):
            add(letter, f"lib/py/bbx/{m}.py")
        add(letter, driver_rel(suite.get("driver")))
    for cpath in git(root, "ls-files", "*bbx.toml").split():
        if cpath == "bbx.toml":
            continue
        try:
            cfg = C.load(os.path.join(root, cpath))
            kind = C.kind_of(cfg)
        except Exception:
            continue
        if kind in LETTER:
            add(LETTER[kind], driver_rel(cfg.get("suite", {}).get("driver")))
    return named


def driver_rel(value):
    """A bare driver NAME is ours; a path names another tree's (R26) and is
    outside this universe, so it is dropped rather than mangled."""
    if not value or "/" in value:
        return ""
    return f"drivers/{value}.sh"


def seeds(root, univ):
    named = named_by_kind(root, univ)
    out = {}
    for L in named:
        others = set().union(*[named[o] for o in named if o != L]) if len(named) > 1 else set()
        out[L] = named[L] - others
    return out


def importers(root, univ):
    """module relpath -> the universe modules that IMPORT it, transitively.

    The trace's python half records what was LOADED, not what was run (the
    instrument's declared limit), so a seed hit can be the side effect of a
    SHARED module's import. Measured at bbx-19: `compare_exact.py` and
    `compare_set.py` both import `docset.py`, so the document-set seed fired on
    `gates/adapters.sh` — a command-line gate — and it read `DC`. The third kind
    is the detector of exactly this, which is BBX-25's own argument.

    bbx-11 could not see it: with two kinds, every gate that ran the exact
    family was a document-set gate, so the wrong attribution was invisible."""
    direct = {}
    for rel in univ:
        if not rel.startswith("lib/py/bbx/") or not rel.endswith(".py"):
            continue
        src = open(os.path.join(root, rel), errors="replace").read()
        names = set(re.findall(r"^\s*from \.(?:\s*)import ([a-z_][a-z0-9_]*)", src, re.M))
        names |= set(re.findall(r"^\s*from \.([a-z_][a-z0-9_]*) import", src, re.M))
        names |= set(re.findall(r"^\s*import bbx\.([a-z_][a-z0-9_]*)", src, re.M))
        direct[rel] = {f"lib/py/bbx/{n}.py" for n in names} & set(univ)
    closure = {}
    for rel in direct:
        seen, todo = set(), list(direct[rel])
        while todo:
            m = todo.pop()
            if m in seen:
                continue
            seen.add(m)
            todo.extend(direct.get(m, ()))
        closure[rel] = seen
    out = {}
    for rel, imported in closure.items():
        for m in imported:
            out.setdefault(m, set()).add(rel)
    return out


# ----------------------------------------------------- the shadow and its trace

def header_end(lines):
    """The last line of the LEADING COMMENT BLOCK after the shebang (R30).

    0 when there is none — the caller then inserts after the shebang and the
    file has no header to end. A bare `#` continues the block; the first
    non-comment line ends it."""
    last = 0
    for i, line in enumerate(lines[1:], start=2):
        if line.startswith("#"):
            last = i
        else:
            break
    return last


def instrument(shadow, trace, univ, after_shebang=False):
    """One trace line per executed sh file; lib/sh files are SOURCED, so their
    line goes at the end. Returns the list of files instrumented."""
    done = []
    execs = [p for p in univ if (p.startswith("bin/") or
                                 (p.startswith("drivers/") and p.endswith(".sh")))]
    sourced = [p for p in univ if p.startswith("lib/sh/") and p.endswith(".sh")]
    for rel in execs:
        path = os.path.join(shadow, rel)
        if not os.path.exists(path):
            continue
        lines = open(path, errors="replace").read().splitlines(keepends=True)
        if not lines:
            continue
        n = 1 if after_shebang else (header_end([l.rstrip("\n") for l in lines]) or 1)
        probe = "printf '%%s\\n' '%s' >> '%s'\n" % (rel, trace)
        with open(path, "w") as f:
            f.writelines(lines[:n])
            f.write(probe)
            f.writelines(lines[n:])
        os.chmod(path, 0o755)
        done.append(rel)
    for rel in sourced:
        path = os.path.join(shadow, rel)
        if not os.path.exists(path):
            continue
        with open(path, "a") as f:
            f.write("\nprintf '%%s\\n' '%s' >> '%s'\n" % (rel, trace))
        done.append(rel)
    site = os.path.join(shadow, "lib", "py", "sitecustomize.py")
    if os.path.isdir(os.path.dirname(site)):
        with open(site, "w") as f:
            f.write(SITECUSTOMIZE % {"trace": trace, "root": shadow + os.sep})
        done.append("lib/py/sitecustomize.py")
    return done


SITECUSTOMIZE = '''\
import atexit, os, sys
_T = %(trace)r
# REALPATH on both sides, never the path as written. A gate derives its own home
# with `cd "$(dirname "$0")/.." && pwd`, and what `pwd` reports depends on how the
# gate was started: with a cwd handed to the process (no matching PWD in its
# environment) the shell reports the PHYSICAL path, so on macOS a shadow under
# TMPDIR is imported as /private/var/... while the instrument had written
# /var/... and startswith() was False for EVERY module. Measured at bbx-19: 30 of
# 44 harness files read as "executed by NO gate" — a plausible number and pure
# garbage (BBX-16). The same run under build/ traced correctly only because no
# symlink lies in that path, which is luck, not design.
_ROOT = os.path.realpath(%(root)r) + os.sep
def _keep(p, seen):
    if not p:
        return
    r = os.path.realpath(p)
    if r.startswith(_ROOT) and "/lib/py/bbx/" in r:
        seen.add(os.path.relpath(r, _ROOT))
def _dump():
    seen = set()
    for m in list(sys.modules.values()):
        _keep(getattr(m, "__file__", None), seen)
    _keep(sys.argv[0] if sys.argv else "", seen)
    if seen:
        with open(_T, "a") as fh:
            for s in sorted(seen):
                print(s, file=fh)   # no escape here on purpose: a newline escape in this template collapsed one level and broke the emitted file (bbx-19)
atexit.register(_dump)
'''


def build_shadow(root, out, univ, after_shebang=False, refreeze=""):
    shadow = os.path.join(out, "shadow")
    trace = os.path.join(out, "trace.txt")
    if os.path.exists(shadow):
        subprocess.run(["rm", "-rf", shadow], check=True)
    os.makedirs(shadow)
    tar = subprocess.Popen(["git", "-C", root, "archive", "HEAD"], stdout=subprocess.PIPE)
    subprocess.run(["tar", "-x", "-C", shadow], stdin=tar.stdout, check=True)
    tar.stdout.close()
    tar.wait()
    head = identity(root)
    commit = git(root, "rev-parse", "HEAD").strip()
    instrumented = instrument(shadow, trace, univ, after_shebang)
    sh_commit(shadow, "shadow-instrumented")
    if refreeze:
        # A subject whose OWN expectations are keyed by its content (R38's
        # identity) is legitimately MOVED by instrumentation: BBX's
        # fixture/selfgates reads "THE HARNESS HAS MOVED" and gates/adapters.sh
        # FAILs in the shadow, which the refusal above would then read as a
        # contaminated trace (measured at bbx-19, exit 1 on `--only adapters`).
        # So the subject is given one command to re-derive those expectations
        # INSIDE the throwaway shadow, after the first commit because the key is
        # of the COMMIT. The four identity trees are untouched by such a
        # regeneration, so the key is stable across the second commit.
        env = {**os.environ, "BBX_HOME": shadow,
               "PYTHONPATH": os.path.join(shadow, "lib", "py")}
        r = run(["sh", "-c", refreeze], cwd=shadow, env=env)
        print(f"  refreeze   `{refreeze}` in the shadow: exit {r.returncode}")
        if r.returncode:
            for line in (r.stdout + r.stderr).splitlines()[-6:]:
                print(f"      {line}")
            raise RuntimeError(f"--shadow-refreeze failed (exit {r.returncode})")
        sh_commit(shadow, "shadow-refrozen")
    return shadow, trace, head, commit, instrumented


def sh_commit(shadow, message):
    run(["git", "-C", shadow, "init", "-q"])
    run(["git", "-C", shadow, "add", "-A"])
    run(["git", "-C", shadow, "-c", "user.name=fc", "-c", "user.email=fc@fc",
         "commit", "-qm", message])


# ------------------------------------------------------------ running the gates

def harness_home():
    """The HARNESS's own root, never the subject's: the classifier that reads a
    shadow gate's verdict is BBX's (the stronger copy, [BBH-82]), so a synthetic
    subject tree needs no `bin/bbx` of its own."""
    return os.environ.get("BBX_HOME") or os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))


def classify(rc, log):
    home = harness_home()
    r = run([os.path.join(home, "bin", "bbx"), "classify", str(rc), log],
            env={**os.environ, "PYTHONPATH": os.path.join(home, "lib", "py")})
    text = (r.stdout or r.stderr).strip()
    return text.split("\t")[0].split()[0] if text else "?"


def run_gates(shadow, trace, out, names, extra_env):
    os.makedirs(os.path.join(out, "files"), exist_ok=True)
    os.makedirs(os.path.join(out, "logs"), exist_ok=True)
    rows = []
    for name in names:
        gate = os.path.join(shadow, "gates", f"{name}.sh")
        log = os.path.join(out, "logs", f"{name}.log")
        files = os.path.join(out, "files", f"{name}.txt")
        if os.path.exists(trace):
            os.remove(trace)
        if not os.path.exists(gate):
            open(files, "w").close()
            open(log, "w").write(f"MISSING: {gate}\n")
            rows.append((name, 1, 0, "MISSING"))
            continue
        # BBX_FILE_CENSUS_SHADOW tells a gate it is inside an instrumented shadow, so a gate
        # whose question is UNANSWERABLE there can SKIP and say why. Measured at bbx-20: the
        # instrument writes lib/py/sitecustomize.py and `git add -A` commits it, so the
        # shadow's universe permanently holds a harness file the tree's census register can
        # never contain — gates/census_register.sh therefore read FAIL in every shadow, the
        # contamination rule discarded the run, and the register could only be completed by a
        # run that could not complete (G46).
        env = {**os.environ, "PYTHONPATH": os.path.join(shadow, "lib", "py"),
               "PYTHONDONTWRITEBYTECODE": "1", "BBX_FILE_CENSUS_SHADOW": "1", **extra_env}
        t0 = time.time()
        r = run(["sh", os.path.join("gates", f"{name}.sh")], cwd=shadow, env=env)
        secs = int(round(time.time() - t0))
        open(log, "w").write(r.stdout + r.stderr)
        seen = sorted(set(open(trace).read().split())) if os.path.exists(trace) else []
        open(files, "w").write("".join(s + "\n" for s in seen))
        rows.append((name, r.returncode, secs, classify(r.returncode, log)))
    with open(os.path.join(out, "verdicts.tsv"), "w") as f:
        f.write("gate\texit\tseconds\tverdict\n")
        for name, rc, secs, v in rows:
            f.write(f"{name}\t{rc}\t{secs}\t{v}\n")
    return rows


def read_run(out):
    """A KEPT run read back: the identity, every gate's verdict, and how many
    files were instrumented — all three, because a render under `--reuse` needs
    the instrumented count for row A4 and read it as unset on its first try
    (UnboundLocalError, caught by this gate's own regeneration at bbx-19). `--reuse`
    exists so a gate that costs minutes can run its CONTROLS against the same
    measurement instead of re-measuring once per control (the alternative was
    one whole battery per control)."""
    run_txt = os.path.join(out, "run.txt")
    if not os.path.exists(run_txt):
        raise RuntimeError(f"--reuse: {run_txt} is missing — there is no kept run here")
    keys = dict(l.rstrip("\n").split("\t", 1) for l in open(run_txt) if "\t" in l)
    rows = []
    with open(os.path.join(out, "verdicts.tsv")) as f:
        head = f.readline().rstrip("\n").split("\t")
        for line in f:
            cells = dict(zip(head, line.rstrip("\n").split("\t")))
            rows.append((cells["gate"], int(cells["exit"]), int(cells["seconds"]),
                         cells["verdict"]))
    return keys["identity"], rows, int(keys.get("instrumented", 0))


# ----------------------------------------------------------------- the analysis

def gate_kinds(root, out, rows, seed, static_names, needs_env, imps):
    """A seed hit counts only when nothing else in the same trace EXPLAINS it.

    If a module in the trace imports the seed and is not itself a seed of that
    kind, the hit is the importer's side effect and is dropped — otherwise a
    shared comparator that imports one kind's module would file every gate
    under that kind (measured at bbx-19 on `gates/adapters.sh`)."""
    kinds = {}
    all_seeds = set().union(*seed.values()) if seed else set()
    for name, _rc, _s, _v in rows:
        p = os.path.join(out, "files", f"{name}.txt")
        executed = set(open(p).read().split()) if os.path.exists(p) else set()
        ks = set()
        for L, files in seed.items():
            for f in files & executed:
                explainers = (imps.get(f, set()) & executed) - all_seeds
                if not explainers:
                    ks.add(L)
                    break
        if name in static_names and needs_env and needs_env in uncomment(
                os.path.join(root, "gates", f"{name}.sh")):
            ks.add("F")
        kinds[name] = ks or {"K"}
    return kinds


def reachability(out, rows, univ):
    reach = {f: [] for f in univ}
    for name, _rc, _s, _v in rows:
        p = os.path.join(out, "files", f"{name}.txt")
        for f in (open(p).read().split() if os.path.exists(p) else []):
            reach.setdefault(f, []).append(name)
    return {f: sorted(gs) for f, gs in reach.items()}


def categorise(univ, reach, kinds):
    cat = {}
    for f in univ:
        gs = reach.get(f, [])
        classes = set()
        for g in gs:
            classes |= kinds.get(g, set())
        for label, test in CATEGORIES:
            if test(classes):
                cat.setdefault(label, []).append((f, len(gs), gs))
                break
    return cat


# ------------------------------------------------------------------- rendering

def render(out, head, univ, rows, kinds, reach, cat, portable, static, instrumented):
    skipped = sorted(n for n, _rc, _s, v in rows if v == "SKIP")
    def letters(name):
        return "".join(c for c in "KFDC" if c in kinds[name]) or "K"
    L = []
    A = []
    counts = {label: len(v) for label, v in cat.items()}
    khist = {}
    for name in kinds:
        khist[letters(name)] = khist.get(letters(name), 0) + 1
    A.append(("A1", "tracked files under lib/, bin/, drivers/ (README.md excluded) — the universe",
              len(univ), "`git ls-files lib bin drivers | grep -vc '\\.md$'`"))
    A.append(("A2", "registered gates (both tiers)", len(portable) + len(static),
              "`grep -hv '^#' gates/portable.txt gates/static.txt | wc -l`"))
    A.append(("A3", "gates run in the shadow, each once, alone, with a fresh trace",
              len(rows), "§B.1, one row each"))
    A.append(("A4", "harness files instrumented (one trace line each)", len(instrumented),
              "§C: every `bin/*`, `drivers/*.sh`, `lib/sh/*.sh` plus `lib/py/sitecustomize.py`"))
    i = 5
    for word in sorted(khist):
        A.append((f"A{i}", f"gates whose derived kind is `{word}`", khist[word], "§B.1"))
        i += 1
    for label, _t in CATEGORIES:
        if label in counts or label == "REACHED BY NO GATE":
            A.append((f"A{i}", f"files: {label}", counts.get(label, 0), "§B.2"))
            i += 1
    A.append((f"A{i}", "files executed by exactly one gate",
              sum(1 for f in univ if len(reach.get(f, [])) == 1), "§B.2, the `gates` column"))
    i += 1
    A.append((f"A{i}", "files executed by 15 gates or more",
              sum(1 for f in univ if len(reach.get(f, [])) >= 15), "§B.2, the `gates` column"))

    L.append(BEGIN)
    L.append("")
    L.append(f"**Measured at harness identity `{head}`** (R38's whole-set key over `bin`, "
             f"`lib`, `drivers`, `gates` — NOT `HEAD`, so a commit that only rewrites this "
             f"document leaves it checkable) over {len(univ)} tracked files under `lib/`, `bin/`, "
             f"`drivers/` (`*.md` excluded) and {len(rows)} gates, each run ONCE in the shadow "
             f"with a fresh trace. `bbx file-census --check` fails on any line below. "
             + (f"**{len(skipped)} gate(s) SKIPPED in the shadow** and so under-report what "
                f"they reach: {', '.join('`' + g + '`' for g in skipped)}."
                if skipped else "No gate skipped in the shadow."))
    L.append("")
    L.append("## A. Counts")
    L.append("")
    L.append("| id | dimension | count | command / derivation |")
    L.append("|---|---|---|---|")
    for idv, dim, n, how in A:
        L.append(f"| {idv} | {dim} | {n} | {how} |")
    L.append("")
    L.append("### B.1 Gates, by derived kind, with the number of harness files each "
             "executed and its verdict in the shadow")
    L.append("")
    # NO SECONDS COLUMN. Runtimes move between runs of the same 30 gates (measured at
    # bbx-19: 12 of 30 rows differed by 1-4 s between two runs whose every file count,
    # kind and verdict was identical), so a checked block carrying them could never be
    # stable and `--check` would fail on every second run — tolerating that difference
    # is exactly what BBX-14 forbids, and the answer is to not freeze a non-deterministic
    # field rather than to excuse it. Per-gate runtimes live in the kept run's
    # verdicts.tsv, which is where a runtime question is answered.
    L.append("| gate | tier | kind | files executed | shadow verdict |")
    L.append("|---|---|---|---|---|")
    for name, _rc, _secs, verdict in rows:
        tier = "portable" if name in portable else "static" if name in static else "-"
        n = len(open(os.path.join(out, "files", f"{name}.txt")).read().split())
        L.append(f"| `{name}` | {tier} | {letters(name)} | {n} | {verdict} |")
    L.append("")
    L.append("### B.2 Files, by category, with every gate that executed them")
    for label, _t in CATEGORIES:
        if label not in cat and label != "REACHED BY NO GATE":
            continue
        L.append("")
        rows_here = cat.get(label, [])
        L.append(f"**{label}: {len(rows_here)}**")
        L.append("")
        if not rows_here:
            L.append("(none)")
            continue
        L.append("| file | gates | executed by |")
        L.append("|---|---|---|")
        for f, n, gs in sorted(rows_here):
            L.append(f"| `{f}` | {n} | {' '.join(gs) or '—'} |")
    L.append("")
    L.append(END)
    return "\n".join(L) + "\n"


def splice(document, block):
    with open(document) as f:
        text = f.read()
    if BEGIN not in text or END not in text:
        raise RuntimeError(f"{document} carries no generated block "
                           f"(expected the BEGIN and END markers)")
    head, rest = text.split(BEGIN, 1)
    _old, tail = rest.split(END, 1)
    return head + block.rstrip("\n") + tail


# ------------------------------------------------- the frozen kind-sets (R39)

def measured_kindsets(univ, reach, kinds):
    out = {}
    for f in univ:
        ks = set()
        for g in reach.get(f, []):
            ks |= kinds.get(g, set())
        out[f] = "".join(c for c in "KFDC" if c in ks)
    return out


def render_frozen(head, kindsets):
    L = ["# expected/file_census.toml — the FROZEN kind-set of every harness file",
         "# (R39; provenance class `self`: BBX's measurement of BBX, which locks",
         "# CURRENCY and never correctness — CLAUDE.md §3.3). Generated by",
         "# `bbx file-census --self --freeze`; compared SHRINK-ONLY: a file that",
         "# lost a kind FAILs naming it, a file reached by NO gate FAILs always,",
         "# a gained kind is a NOTE and re-freezes. Never hand-edited (BBX-21).",
         "",
         "[spec]",
         'class = "self"',
         "# measured_at is R38's whole-set key over bin, lib, drivers, gates — NOT HEAD",
         f'measured_at = "{head}"',
         'mode = "shrink-only"',
         ""]
    for i, (f, ks) in enumerate(sorted(kindsets.items()), start=1):
        L.append(f"[f{i}]")
        L.append(f'file = "{f}"')
        L.append(f'kinds = "{ks}"')
        L.append("")
    return "\n".join(L)


def load_frozen(path):
    from . import toml_subset
    data = toml_subset.load(path)
    rows = {}
    for key, tbl in data.items():
        if key == "spec" or not isinstance(tbl, dict):
            continue
        if "file" not in tbl or "kinds" not in tbl:
            raise RuntimeError(f"{path}: [{key}] needs both `file` and `kinds`")
        if tbl["file"] in rows:
            raise RuntimeError(f"{path}: `{tbl['file']}` frozen twice — hand-editing (BBX-17)")
        rows[tbl["file"]] = tbl["kinds"]
    return data.get("spec", {}), rows


def compare_frozen(frozen, measured):
    """Shrink-only, both ways. Returns (failures, notes)."""
    bad, notes = [], []
    for f in sorted(frozen):
        if f not in measured:
            bad.append(f"FAIL file-census: `{f}` is frozen and is not in the universe "
                       f"(a dead row, BBX-9)")
            continue
        lost = set(frozen[f]) - set(measured[f])
        if lost:
            bad.append(f"FAIL file-census: `{f}` lost kind(s) {''.join(sorted(lost))} "
                       f"— frozen {frozen[f]}, measured {measured[f] or '(no gate)'}")
    for f in sorted(measured):
        if not measured[f]:
            bad.append(f"FAIL file-census: `{f}` is executed by NO gate "
                       f"(rot class 1, orphan)")
        elif f not in frozen:
            notes.append(f"NOTE: file-census-new {f} {measured[f]}")
        else:
            gained = set(measured[f]) - set(frozen[f])
            if gained:
                notes.append(f"NOTE: file-census-grew {f} {''.join(sorted(gained))}")
    return bad, notes



# --------------------------------------- the register's completeness (R47)

def register_completeness(root, frozen_path):
    """The census REGISTER against the universe, both ways, with NO shadow and no
    gate run (R47, ruled 2026-09-12).

    The census itself is release-scoped (D63) because it runs the whole battery
    inside a shadow, so between releases nothing watched it: measured at bbx-20,
    `expected/file_census.toml` and `docs/census/bbx_files.md` are read by
    `gates/file_census.sh` and this module and by nothing else in the battery. A
    harness file added and brought under no gate therefore read green until the
    next release run.

    Two FAILures and one NOTE, the split ruled by the maintainer and following
    R18's own precedent that the register rotting and the world moving are
    different findings:

      FAIL  a universe file with no frozen row — the new-file case, the likeliest
            rot by far, and the one this check exists for
      FAIL  a frozen row naming a file the universe no longer holds (a dead row,
            BBX-9's other direction)
      NOTE  the register's `measured_at` is not the tree's current harness
            identity — the census is STALE, which is true and loud and never
            fatal, because making it fatal would red the battery on every kernel
            commit until a twenty-minute run

    What it CANNOT do, and says so: prove that a file is REACHED by any gate.
    Only a run with traces can, and that is `gates/file_census.sh`'s job."""
    _spec, rows = load_frozen(frozen_path)
    univ = set(universe(root))
    bad, notes = [], []
    for f in sorted(univ - set(rows)):
        bad.append(f"FAIL register: `{f}` is a tracked harness file with NO frozen "
                   f"census row — it may be reached by no gate and nothing would say so")
    for f in sorted(set(rows) - univ):
        bad.append(f"FAIL register: `{f}` has a frozen census row and is not in the "
                   f"universe (a dead row, BBX-9)")
    frozen_at = _spec.get("measured_at", "")
    now = identity(root)
    if frozen_at != now:
        notes.append(f"NOTE: census-drift register={frozen_at[:12]} tree={now[:12]} "
                     f"(the harness moved past the census; the release gate re-measures it)")
    return bad, notes, len(univ), len(rows)

# ------------------------------------------------------------------------- main

def main(argv):
    root = out = document = frozen_path = None
    only = None
    refreeze = ""
    reuse = False
    check_register = False
    after_shebang = check = freeze = False
    extra_env = {}
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--self":
            root = os.environ.get("BBX_HOME") or os.getcwd()
        elif a == "--root":
            i += 1
            root = argv[i]
        elif a == "--out":
            i += 1
            out = argv[i]
        elif a == "--document":
            i += 1
            document = argv[i]
        elif a == "--frozen":
            i += 1
            frozen_path = argv[i]
        elif a == "--only":
            i += 1
            only = [x for x in argv[i].split(",") if x]
        elif a == "--env":
            i += 1
            k, _, v = argv[i].partition("=")
            extra_env[k] = v
        elif a == "--shadow-refreeze":
            i += 1
            refreeze = argv[i]
        elif a == "--reuse":
            reuse = True
        elif a == "--check-register":
            check_register = True
        elif a == "--insert-after-shebang":
            after_shebang = True
        elif a == "--check":
            check = True
        elif a == "--freeze":
            freeze = True
        else:
            print(f"bbx file-census: unknown argument {a!r}", file=sys.stderr)
            return 2
        i += 1
    if not root:
        print(__doc__, file=sys.stderr)
        return 2
    root = os.path.abspath(root)
    if not out and not check_register:
        print("bbx file-census: --out DIR is required (the run is kept)", file=sys.stderr)
        return 2
    if out:
        out = os.path.abspath(out)
        os.makedirs(out, exist_ok=True)

    if check_register:
        if not frozen_path:
            print("bbx file-census --check-register needs --frozen PATH", file=sys.stderr)
            return 2
        bad, notes, n_univ, n_rows = register_completeness(root, os.path.abspath(frozen_path))
        for n in notes:
            print(n)
        for b in bad:
            print(b)
        print(f"  register   files {n_univ}   rows {n_rows}   missing-rows "
              f"{len([b for b in bad if 'NO frozen' in b])}   dead-rows "
              f"{len([b for b in bad if 'dead row' in b])}")
        return 1 if bad else 0

    cfg = C.load(os.path.join(root, "bbx.toml"))
    univ = universe(root)
    portable, static = registries(root, cfg)
    names = only if only is not None else portable + static
    seed = seeds(root, univ)
    print(f"  universe   {len(univ)} files   gates {len(names)}   "
          f"seeds F={len(seed['F'])} D={len(seed['D'])} C={len(seed['C'])}")
    if reuse:
        head, rows, n_instr = read_run(out)
        instrumented = ["(kept run)"] * n_instr
        print(f"  reuse      {out}   identity {head[:12]}   {len(rows)} kept traces "
              f"(no shadow built, no gate run)")
    else:
        shadow, trace, head, commit, instrumented = build_shadow(
            root, out, univ, after_shebang, refreeze)
        print(f"  shadow     {shadow} at commit {commit[:12]}   identity {head[:12]}   "
              f"instrumented {len(instrumented)} files"
              f"{'   INSERT-AFTER-SHEBANG (G25 reproduced)' if after_shebang else ''}")
        rows = run_gates(shadow, trace, out, names, extra_env)
        with open(os.path.join(out, "run.txt"), "w") as f:
            f.write(f"identity\t{head}\ncommit\t{commit}\n"
                    f"instrumented\t{len(instrumented)}\n")
        for name, _rc, secs, verdict in rows:
            print(f"    {name:24s} {verdict:8s} {secs}s")
    # A gate that FAILED executed less than it executes in the tree, so its trace is
    # CONTAMINATED and the run is discarded. A gate that SKIPPED asserted nothing and misled
    # nobody, so it does not contaminate — but it DOES under-report its own reach, which is a
    # limit this run STATES rather than absorbs (BBX-30).
    skipped_gates = sorted(n for n, _rc, _s, v in rows if v == "SKIP")
    dirty = [(n, v) for n, _rc, _s, v in rows if v not in ("PASS", "SKIP")]
    if dirty:
        for name, verdict in dirty:
            print(f"REFUSED: file-census: `{name}` is {verdict} in the shadow — its trace is "
                  f"CONTAMINATED, so the run is discarded, never adjusted (CLAUDE.md §1)")
        return 1
    for _g in skipped_gates:
        print(f"NOTE: census-skipped {_g} (it asserted nothing in the shadow, so the files it "
              f"reaches are under-reported by this run)")

    imps = importers(root, univ)
    kinds = gate_kinds(root, out, rows, seed, set(static),
                       C.get(cfg, "registries.static_needs_env"), imps)
    reach = reachability(out, rows, univ)
    cat = categorise(univ, reach, kinds)
    measured = measured_kindsets(univ, reach, kinds)
    print("  gate kinds " + " ".join(
        f"{n}={''.join(c for c in 'KFDC' if c in kinds[n]) or 'K'}" for n, *_ in rows))

    rc = 0
    if frozen_path:
        frozen_path = os.path.abspath(frozen_path)
        if freeze:
            open(frozen_path, "w").write(render_frozen(head, measured))
            print(f"  froze      {len(measured)} kind-set rows into {frozen_path}")
        else:
            try:
                _spec, rows_f = load_frozen(frozen_path)
            except Exception as exc:
                print(f"FAIL file-census: {exc}")
                return 1
            bad, notes = compare_frozen(rows_f, measured)
            for n in notes:
                print(n)
            for b in bad:
                print(b)
            print(f"  kind-sets  frozen {len(rows_f)} measured {len(measured)} "
                  f"failures {len(bad)} notes {len(notes)}")
            if bad:
                rc = 1

    if document:
        document = os.path.abspath(document)
        block = render(out, head, univ, rows, kinds, reach, cat, portable, static, instrumented)
        new = splice(document, block)
        if check:
            old = open(document).read()
            if old == new:
                print(f"  document   {os.path.relpath(document, root)} is the run's own text")
            else:
                a, b = old.splitlines(), new.splitlines()
                for n, (x, y) in enumerate(zip(a, b), start=1):
                    if x != y:
                        print(f"FAIL file-census: {os.path.relpath(document, root)}:{n} "
                              f"differs from the run")
                        print(f"       document: {x}")
                        print(f"       the run : {y}")
                        break
                else:
                    print(f"FAIL file-census: {os.path.relpath(document, root)} has "
                          f"{len(a)} lines, the run renders {len(b)}")
                rc = 1
        else:
            open(document, "w").write(new)
            print(f"  document   {os.path.relpath(document, root)} regenerated "
                  f"({len(block.splitlines())} generated lines)")
    return rc


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
