#!/usr/bin/env python3
"""fakecli.py — the COMMAND-LINE FIXTURE's tool: BBX's fixture subject of kind B (docs/generality.md;
docs/plans/S4.md §4). GENERATED by mkfakecli.py — do not edit; regenerate.

Deterministic: a function of its arguments, its stdin and the ONE environment variable it declares —
and nothing else. Every feature is an OPTION (a tool's contract is its command line):

    fakecli.py list [--unordered]                 one line per record, `<rank> <name> <id> <weight>`,
                                                  by rank; --unordered in the table's own order
    fakecli.py show <name> [--emit-json]          the record as `<key>=<value>` lines, or as ONE JSON object
    fakecli.py stat --band <field> --seed <n>     ONE JSON object {"seed": n, "<field>": size(n)}: the
                                                  field varies with the seed inside a designed band
    fakecli.py join                               every stdin line prefixed with its index, `<i>:<line>`
    fakecli.py report --emit <file>               writes <file> (the records as JSON) and says so
  feature options (any command):
    --nondet          appends `now=<nanoseconds>` — the clock mixed in (the NONDETERMINISTIC control)
    --crash-at <n>    dies by SIGABRT (os.abort) after the n-th stdout line (the guard's control)
    --write-home      writes $HOME/.fakecli first (the sandbox control)
    --sleep <s>       sleeps s seconds first (the timeout control)
  refusals (SMS cliguard's shape: one stderr line naming the thing, exit 2; an unknown record exit 1):
    an unknown option; an option without its value; no command; an unknown command; show with no name
  the environment: FAKECLI_SALT, when SEEN, appends `salt=<value>` — the control that the driver's scrub
    is measured (called directly: differs; through the driver: identical; through the scenario's [env]:
    reaches the tool)
"""
import json
import os
import sys
import time

RECORDS = [('Maren', '4D2B', 83, 6, ('ash', 'elm')), ('Orsolya', '7E19', 26, 2, ('oak',)), ('Perrin', '1B8C', 94, 8, ('elm', 'fir', 'yew')), ('Quillon', '9A35', 17, 4, ('fir',)), ('Rosalind', '3F60', 48, 1, ('yew', 'ash')), ('Sable', '6C97', 35, 9, ('oak', 'elm')), ('Tobin', '2E4A', 76, 3, ('ash',)), ('Ulric', '8B13', 59, 7, ('fir', 'oak')), ('Vesna', '5A7D', 82, 5, ('yew',))]
BAND_BASE, BAND_MUL, BAND_MOD = (231, 29, 41)
SALT_ENV = 'FAKECLI_SALT'
COMMANDS = ("list", "show", "stat", "join", "report")
FLAGS = ("--nondet", "--write-home", "--emit-json", "--unordered")
OPTIONS_WITH_ARG = ("--crash-at", "--seed", "--emit", "--band", "--sleep")


def refuse(message, status):
    sys.stdout.flush()
    sys.stderr.write(f"fakecli: {message}\n")
    sys.exit(status)


class Out:
    """stdout, one line at a time, flushed — so a crash after n lines leaves exactly n lines behind."""
    def __init__(self, crash_at):
        self.n = 0
        self.crash_at = crash_at

    def line(self, text):
        sys.stdout.write(text + "\n")
        sys.stdout.flush()
        self.n += 1
        if self.crash_at is not None and self.n >= self.crash_at:
            os.abort()


def parse(argv):
    opts, pos = {}, []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a.startswith("--"):
            if a in FLAGS:
                opts[a] = True
            elif a in OPTIONS_WITH_ARG:
                if i + 1 >= len(argv):
                    refuse(f"option '{a}' needs a value", 2)
                opts[a] = argv[i + 1]
                i += 1
            else:
                refuse(f"unknown option '{a}'", 2)
        else:
            pos.append(a)
        i += 1
    return opts, pos


def as_object(r):
    return {"name": r[0], "id": r[1], "weight": r[2], "rank": r[3], "tags": list(r[4])}


def canon(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def main(argv):
    opts, pos = parse(argv)
    if not pos:
        refuse("no command", 2)
    cmd = pos[0]
    if cmd not in COMMANDS:
        refuse(f"unknown command '{cmd}'", 2)
    if "--sleep" in opts:
        time.sleep(int(opts["--sleep"]))
    if "--write-home" in opts:
        with open(os.path.join(os.environ.get("HOME", "."), ".fakecli"), "w") as fh:
            fh.write("visited\n")
    out = Out(int(opts["--crash-at"]) if "--crash-at" in opts else None)
    if cmd == "list":
        rows = RECORDS if "--unordered" in opts else sorted(RECORDS, key=lambda r: r[3])
        for r in rows:
            out.line(f"{r[3]} {r[0]} {r[1]} {r[2]}")
    elif cmd == "show":
        if len(pos) < 2:
            refuse("show needs a name", 2)
        hits = [r for r in RECORDS if r[0] == pos[1]]
        if not hits:
            refuse(f"no record '{pos[1]}'", 1)
        obj = as_object(hits[0])
        if "--emit-json" in opts:
            out.line(canon(obj))
        else:
            for k in ("name", "id", "weight", "rank", "tags"):
                out.line(f"{k}={obj[k] if k != 'tags' else ','.join(obj[k])}")
    elif cmd == "stat":
        seed = int(opts.get("--seed", "1"))
        field = opts.get("--band", "size")
        out.line(canon({"seed": seed, field: BAND_BASE + (seed * BAND_MUL) % BAND_MOD}))
    elif cmd == "join":
        for i, line in enumerate(sys.stdin.read().splitlines(), start=1):
            out.line(f"{i}:{line}")
    elif cmd == "report":
        if "--emit" not in opts:
            refuse("report needs --emit <file>", 2)
        data = (canon([as_object(r) for r in RECORDS]) + "\n").encode("utf-8")
        with open(opts["--emit"], "wb") as fh:
            fh.write(data)
        out.line(f"wrote {opts['--emit']} ({len(data)} bytes)")
    if "--nondet" in opts:
        out.line(f"now={time.time_ns()}")
    salt = os.environ.get(SALT_ENV)
    if salt is not None:
        out.line(f"salt={salt}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
